services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 2020:2020
    volumes:
      - wordpress_data:/var/www/html
      - /run/php:/run/php
    restart: always
    networks:
      - net

  mariadb:
    container_name: mariadb
    # build: ./requirements/mariadb
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    # in case of problem we restart automatically the container
    networks:
      - net
    # restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    #Create a depedency between the 2 container, db will be launched before
    depends_on:
      - mariadb
      - nginx
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    # restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
      - /run/php:/run/php
    networks:
      - net

volumes:
  mariadb_data:
  wordpress_data:

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16